---
title: "Manuscript on dynamic H2O2 and B-cell signaling"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---


## Description

This is the data analysis folder for the flow cytometry data of the manuscript titled: *Dynamic hydrogen peroxide levels reveal a rate-dependent sensitivity in B-cell lymphoma signaling*.



## Abstract

Although in vivo extracellular microenvironments are dynamic, most in vitro studies are conducted under static conditions. Here, we exposed diffuse large B-cell lymphoma (DLBCL) cells to gradient increases in the concentration of hydrogen peroxide (H2O2), thereby capturing some of the dynamics of the tumour microenvironment. Subsequently, we measured the phosphorylation response of B-cell receptor (BCR) signalling proteins CD79a, SYK and PLCγ2 at a high temporal resolution via single-cell phospho-specific flow cytometry. We demonstrated that the cells respond bimodally to static extracellular H2O2, where the percentage of cells that respond is mainly determined by the concentration. Computational analysis revealed that the bimodality results from a combination of a steep dose-response relationship and cell-to-cell variability in the response threshold. Dynamic gradient inputs of varying durations indicated that the H2O2 concentration is not the only determinant of the signalling response, as cells exposed to more shallow gradients respond at lower H2O2 levels. A minimal model of the proximal BCR network qualitatively reproduced the experimental findings and uncovered a rate-dependent sensitivity to H2O2, where a lower rate of increase correlates to a higher sensitivity. These findings will bring us closer to understanding how cells process information from their complex and dynamic in vivo environments.



## In this repository

[Gradient profiles](z_profiles.html) contains the generation of experimental pump profiles for gradient inputs.

[Gating](a_gating.html) contains the gating strategy for all analyses.

[Annotation](b_annotation.html) contains the annotation of the gated data with experimental metadata.

[Paper figs](e_paper_figs.html) contains the main and supplementary figures for the paper.



## Experiments

DS085: LinGradient_Conc

DS095: DetailedStep_Conc

DS096: LinQuadGradient_HighConc

DS097: LinGradient_LowConc

