---
title: "f_other"
author: "mwitmond"
date: "2023-05-08"
output:
  workflowr::wflow_html:
    toc: TRUE
    toc_float: 
      collapsed: FALSE
    toc_depth: 3
    code_folding: hide
editor_options:
  chunk_output_type: console
---


## Set-up

```{r setup, message=F, warning=F}
knitr::opts_chunk$set(
  message = F, warning = F, echo = T, eval = F
)

# Load required packages
source("code/packages_FACS.R", local = knitr::knit_global())
```

```{r fig_settings}
row_order = c("A", "B", "C", "D", "E", "F", "G", "H")
col_order = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12")
panel_labels <- c("A", "B", "C","D", "E", "F", "G", "H", "I", "J", "K", "L", "M")

textsize <- theme(axis.text.x = element_text(colour = "grey", size = 12, face = "bold"),
                  axis.text.y = element_text(colour = "grey", size = 12, face = "bold"),
                  axis.title = element_text(colour = "black", size = 12, face = "bold"), 
                  # legend.title = element_text(colour = "black", size = 12, face = "bold"), 
                  legend.title = element_blank(), 
                  legend.text = element_text(colour = "grey", size = 12, face = "bold"), 
                  strip.text.x = element_text(colour = "black", size = 12, face = "bold")
)

textsize_small <- theme(text = element_text(size = 7, family = "sans", colour = "black"),
                        plot.title = element_text(size = 8)
)

colors_dark9 <- c("#4daf4a", "#984ea3", "#ffff33", "#ff7f00", "#e41a1c", "#f781bf", "#a65628", "#999999", "#377eb8")
colors_light12 <- c("#8dd3c7","#ffffb3","#bebada","#fb8072","#80b1d3","#fdb462","#b3de69","#fccde5","#d9d9d9","#bc80bd","#ccebc5","#ffed6f")
colors_paired10 <- c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fdbf6f", "#ff7f00", "#cab2d6", "#6a3d9a", "#fb9a99", "#e31a1c")
```
